## Model cross border connectors as NTCs
In Nexus-e, cross-border lines used to be represented like normal AC lines with a reactance and had to obey Kirchoff’s laws regarding power flows. Now, the flows on the cross-border lines can follow normal NTC limits (the flow is not governed by the line reactance) and can have different limits in each direction. Jared have already setup two versions of the v48 input data Excel files to define the cross-border lines as either NTCs (`Nexuse_DB-Input_v48_TYNDP24-DE09_CentIvPV_xbNTC.xlsx`) or as AC lines (`Nexuse_DB-Input_v48_TYNDP24-DE09_CentIvPV_xbAC.xlsx`). You will see a column in the branch data named ‘Line Type’ where each line can either be defined as ‘AC’, ‘NTC’, or ‘DC’. Note that the DC line also allows a line loss factor as a percentage of the line flow, the recommended default for this is 7%. But the DC line type has not been tested to the same extent as the NTC line type.

Changing to the NTC cross border lines should be less restrictive and allow us to better represent the different limits applied to flows in each direction. Changing to use the NTC cross border limits is recommended.