# Run CentIv for year 2020
[[modules]]
name = "centiv"
[modules.parameters]
idScenario = 2
# Update investments from CentIv 2020
[[modules]]
name = "update_investments"
[modules.parameters]
startyear = 2
endyear = 5
scenYear = 2020


# Run CentIv for year 2050
[[modules]]
name = "centiv"
[modules.parameters]
idScenario = 5
# Update investments from CentIv 2050
[[modules]]
name = "update_investments"
[modules.parameters]
startyear = 2
endyear = 5
scenYear = 2050


# Run simulation postprocess
[[modules]]
name = "postprocess"