project:
  type: website
theme:
  light: flatly
  dark: darkly
toc: true
metadata-files:
  - reference/_sidebar.yml

website:
  title: Nexus-e
  back-to-top-navigation: true
  page-navigation: true
  search: 
    location: sidebar

  navbar:
    left:
      - text: Wiki
        href: wiki/home.qmd
      - text: Reference
        file: reference/

  sidebar:
    - title: "Wiki"
      collapse-level: 1
      style: docked
      contents:
        - text: Wiki
          href: wiki/home.qmd
        - text: "---" 
        - section: Get started
          contents:
            - text: Install
              href: wiki/get-started/install.qmd
            - text: Run
              href: wiki/get-started/run.qmd
            - text: Configure
              href: wiki/get-started/configure.qmd
            - text: Modules
              href: wiki/get-started/modules.qmd
        - section: Scenarios
          contents:
            - text: Upload a scenario
              href: wiki/scenarios/upload.qmd
            - text: TYNDP24
              href: wiki/scenarios/tyndp24.qmd
            - text: Nodal hourly load
              href: wiki/scenarios/nodal-hourly-load.qmd
            - text: NTC
              href: wiki/scenarios/ntc.qmd
            - text: Europe
              href: wiki/scenarios/europe.qmd
        - section: How-to
          contents:
            - text: Work on Euler
              href: wiki/how-to/work-on-euler.qmd
            - text: Start parallel runs on Euler
              href: wiki/how-to/start-parallel-runs-on-euler.qmd
        - section: Discussions
          contents:
            - text: Input data analysis
              href: wiki/discussions/input-data-analysis.qmd
            - text: Performance analysis
              href: wiki/discussions/performance-analysis.qmd
            - text: Output files
              href: wiki/discussions/output-files.qmd
            - text: Scenario lifecycle
              href: wiki/discussions/scenario-lifecycle.qmd
        - section: Developer guide
          contents:
            - text: How to contribute
              href: wiki/developer-guide/how-to-contribute.qmd
            - text: Write tests
              href: wiki/developer-guide/tests.qmd
            - text: Style guide
              href: wiki/developer-guide/style-guide.qmd
            - text: SOLID principles
              href: wiki/developer-guide/solid-principles.qmd

quartodoc:
  package: null
  source_dir: src
  title: Reference
  dir: reference
  sidebar: 
    file: reference/_sidebar.yml
    collapse-level: 2
  sections:
    - title: API
      package: nexus_e_interface
      contents:
        - name: plugin
          # members: ["Plugin", "Plugin.run", "Plugin.get_default_parameters"]
        - name: scenario
          # members: [DataContext, Scenario, Scenario.create_new_database, Scenario.execute]
        - name: tables
    - title: Plugins
      package: plugins
      contents:
        - name: centiv.nexus_e_plugin
          members: ["NexusePlugin"]
        - name: copy_database.nexus_e_plugin
          members: ["NexusePlugin", "Parameters"]
        - name: delete_database_copies
          members: ["NexusePlugin", "Parameters"]
        - name: postprocess.nexus_e_plugin
          members: ["NexusePlugin", "Parameters"]
        - name: update_inv_costs.nexus_e_plugin
          members: ["NexusePlugin", "Parameters"]
        - name: update_investments.nexus_e_plugin
          members: ["NexusePlugin", "Config"]
        - name: upload_res_data.nexus_e_plugin
          members: ["NexusePlugin", "Parameters"]
        - name: upload_scenario.nexus_e_plugin
          members: ["NexusePlugin", "Config"]
