name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v6
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up virtual environment
        run: uv sync --group dev

      - name: Run tests
        run: uv run pytest --junitxml=junit/test-results/report.xml

      - name: Produce test Summary
        uses: test-summary/action@v2
        with:
          paths: "junit/test-results/*.xml"
        if: always()

      - name: Test build documentation
        run: |
          uv run quartodoc build --config docs/_quarto.yml
          uv run quarto build docs

      
    
    